# application.yml (in config repo)

jwt:
  expiration: 3600000
  secret: 'm0Y%3jF1s9d7@Lz8qWeR!8u6TxCvBnMzm0Y%3jF1s9d7@Lz8qWeR!8u6TxCvBnMz'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

liquibase:
  enabled: true
  change-log: db/db.changelog-master.yml
  drop-first: false

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false

datasource:
  url: jdbc:postgresql://localhost:5432/novaflow
  username: postgres
  password: StiffMedal30  # Use an environment variable for sensitive data
  driver-class-name: org.postgresql.Driver
